apiVersion: v1
data:
  answer: SzhzJGVjcmV0IUFubm90QHQzZCMzMw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"challenge33","namespace":"default"},"stringData":{"answer":"K8s$ecret!Annot@t3d#33"},"type":"generic"}
  creationTimestamp: "2023-05-14T20:58:31Z"
  name: challenge33
  namespace: default
  resourceVersion: "1891"
  uid: 02f40c7a-0319-4936-9d3f-f47b8c4eb642
type: generic
